[tool.poetry]
name = "covidfaq"
version = "0.1.0"
description = ""
authors = ["lp-noel <25254389+lp-noel@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
pylama = "^7.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
